# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c74040e028ccbd2e59866edc4e4b571e186d67ac3e28967a13e82642c3f67d53539ba3699c9887de94cf88c6a512acd679236dfa689c804541ab93abb5d50978

test:
  secret_key_base: 2d22a3b5d66db8c8e248e861a86253232c0662b994e060f21450883e52b3933b6451af7ef1705f6165d365512bc6ca112ced57f39d138fce49eee4779a799e76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
